### ISSUE TITLE
Some troubles with emojis and conversion Markdown to HTML

### ISSUE THREAD

**Issue by liloumuloup** [dalibo/pandocker#75] opened 2019-01-08 13:48 UTC
Hello here,

I just found out that i have another problem with emojis conversion but this time, it's between Markdown and HTML.

I don't think it's linked to #73 but another conversion bug.

Here is an example of the problem : 

## Source Markdown :
```
### ✨ Nouveautés
- blablabla  
- blablabla

### 🔧 Mises à jour
- blablabla  
- blablabla

### 🐛 Corrections
- blablabla  
- blablabla

```

## Converted HTML :
```
<ul>
<li>blablabla<br />
</li>
<li>blablabla</li>
</ul>
<h3 id="mises-Ã -jour">ðŸ”§ Mises Ã  jour</h3>
<ul>
<li>blablabla<br />
</li>
<li>blablabla</li>
</ul>
<h3 id="corrections">ðŸ› Corrections</h3>
<ul>
<li>blablabla<br />
</li>
<li>blablabla</li>
</ul>
```

I'm using this command to convert my file : 
`docker run --rm --privileged  --volume=$CI_PROJECT_DIR:/pandoc dalibo/pandocker:add_emojis --pdf-engine=xelatex magicienletter.md -o magicienletter.html`

I also tried without the `add_emojis ` tag and have the same result.

At this point, i don't know how to fix it. Maybe it is linked to Pandoc version ? According to the official website, it seems to work in the last release of Pandoc.

Is there anything I can do to fix it ?

Thanks for your help.
Best regards.

**Comment by daamien** [comment] 2019-01-14 15:08
Hi ! 

I can't reproduce this error. 

The command :
docker run --rm --privileged --volume=`pwd`:/pandoc dalibo/pandocker:add_emojis --pdf-engine=xelatex magicienletter.md

gives the following output :  


```HTML
<h3 id="nouveautés">✨ Nouveautés</h3>
<ul>
<li>blablabla<br />
</li>
<li>blablabla</li>
</ul>
<h3 id="mises-à-jour">🔧 Mises à jour</h3>
<ul>
<li>blablabla<br />
</li>
<li>blablabla</li>
</ul>
<h3 id="corrections">🐛 Corrections</h3>
<ul>
<li>blablabla<br />
</li>
<li>blablabla</li>
</ul>
````

Did you update the docker image with `docker pull dalibo/pandocker:add_emojis` ?

**Comment by liloumuloup** [comment] 2019-01-15 14:02
Hello @daamien ,

Thanks for your answer. Yes, I updated the docker image and I still have my problem.

Are you using specific settings in your docker image that i might not have ?

**Comment by daamien** [comment] 2019-01-16 14:39
can you send me your markdown file ?

**Comment by liloumuloup** [comment] 2019-01-16 16:48
[magicienletter.md.txt](https://github.com/dalibo/pandocker/files/2765176/magicienletter.md.txt)
Here you are. :)

Best regards.

**Comment by daamien** [comment] 2019-01-17 21:56
Sorry but I can't reproduce. I've added your file to the test suite here :

https://circleci.com/gh/dalibo/pandocker/141?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

and this is the result :

https://github.com/dalibo/pandocker/blob/add_emojis/tests/expected/magicienletter.html

You can check by yourself with : 

```console
$ git clone https://github.com/dalibo/pandocker.git
$ git checkout add_emojis
$ make build
$ TAG=add_emojis make test 
```
and have a look at `tests/output/magicienletter.html`

**Comment by liloumuloup** [comment] 2019-01-23 16:30
I'm sorry but i can't do this test. My docker host is isolated from remote network so i can't clone the repository.

After some researches, i think it might be a trouble with my Linux environment.

Is there a way to have an extract from yours ?

**Comment by daamien** [comment] 2019-01-28 21:30
Not sure what you mean by that... The docker image IS the environment. It should produce the same result with every kind of docker hosts.

I'll merge the emoji branch into `master` and we'll publish the next `stable` version next week. We'll see if you still experience this issue once this is done.

**Comment by daamien** [comment] 2019-02-07 08:22
Hi ! 

I released a new version of the image. Can you update your image with `docker pull dalibo/pandocker:stable` and then try the line below

```
docker run --rm --volume=`pwd`:/pandoc dalibo/pandocker:stable --to html magicienletter.md
```

**Comment by liloumuloup** [comment] 2019-04-05 16:32
Hello @daamien,

Sorry for the delay.

I tried your new image and it seems to work but not in my Gitlab-ci and i can't identify why.

At this point, i think this is more related to Gitlab-ci than your image.

Thank you very much for your help.
Best regards.

**Comment by daamien** [comment] 2019-04-06 07:16
Thanks for the feedback.

For the record, we use this image for multiple gitlab-ci pipelines on a daily basis, and it works fine. Maybe that's a cache  problem. 

Anyway I'm closing this issue. 

Thanks for your contribution to the project !

**Closed by daamien** 2019-04-06 07:16 UTC
