### ISSUE TITLE
ngerman support

### ISSUE THREAD

**Issue by MayerMooBox** [dalibo/pandocker#44] opened 2018-05-16 08:24 UTC
I have tried to make a document in German language with a laTex template that uses the ngerman language pack. I got the following error.

Package babel Error: Unknown option `ngerman'. Either you misspelled it or the language definition file ngerman.ldf was not found.

How can I add support for different languages?

Thanks in advance.
  M.

**Comment by daamien** [comment] 2018-05-21 18:49
Hi  @MayerMooBox !

Thanks for the report ! So far we've used this image mostly with French markdown files.

Your problem occurs because the latex package `ngerman` is missing. This should be fixed with this line : 
https://github.com/dalibo/pandocker/blob/44_german/Dockerfile#L35

I've created a new docker image with the docker tag : `44_german`, you can download it with:

```
docker pull dalibo/pandocker:44_german
```
and then can you use this version with your template and let us know if the problem is fixed ?

By the way, if that's possible, can you send us you german template for testing purpose ?

**Comment by MayerMooBox** [comment] 2018-06-07 20:36
Hi @daamien,
Thanks for the adoption. I have tested the new image and it worked out of the box.

Find also attached a template (including a german markdown-file) to test your images.

[template_de.zip](https://github.com/dalibo/pandocker/files/2081999/template_de.zip)

Issue is fixed!

**Closed** 2018-06-12 09:41 UTC
